### ISSUE TITLE
Pop up 

### ISSUE THREAD

**Issue by zwk5131** [mvavassori/obsidian-web-clipper#4]
Hey , this is a great project. I really love it.
There is only 1 thing .... When you want to safe the website, obsidian opens all the time. It would be nice to just safe it without opening Obsidian. Hope this is the right place to post this....
Keep up the good work.
Thx

**Comment by mvavassori** [comment]
Thank you for your feedback, I wish It was possible to save notes safely to Vaults without opening the app, but the very thing that permits us developers to save notes is a URI link to Obsidian: think of it as a URL that contains the information of the note you just wrote, the same as when you click on a mailto link (it opens your default email application with the recipient already filled in). It's a trick to be able to save notes without actually creating a file on your local computer.

That's because I can't create local files from the extension for security reasons.

The alternative would be to download a file every time you save a note, and that's something i personally wouldn't like (leaving aside other complications).

**Comment by zwk5131** [comment]
Thanks for that answer :D
